# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    labels:
      - devcontainer
      - dependabot
      # TODO: Add CI to rebuild the devcontainer once a month on label. Should just push successful builds closing the
      #       previous PRs.
      - rebuild
    schedule:
      interval: monthly
  - package-ecosystem: "pub"
    directory: "/" # Do it at the workspace root since that is where dart dependency resolution data lives there.
    schedule:
      interval: monthly
    labels:
      - dependabot
      - dart