# This is based on the documentation found [here](https://docs.github.com/en/actions/tutorials/publish-packages/publish-docker-images#publishing-images-to-docker-hub)
name: Dev Container Build
on:
  pull_request:

# Ensure that this workflow gets cancelled on changes.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'devcontainer')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Use the built-in GITHUB_TOKEN secret
      - id: lc
        run: echo "repo=${REPOSITORY,,}" >> ${GITHUB_OUTPUT}
        env:
          REPOSITORY: ${{ github.repository }}
      - name: Build and push Dev Container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ steps.lc.outputs.repo }}/flutter-debian-devcontainer
          cacheFrom: ghcr.io/${{ steps.lc.outputs.repo }}/flutter-debian-devcontainer
          push: false
          platform: linux/amd64
